Django_level_four/learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other')
]

Django_level_four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls'))
]

Django_level_four/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

Django_level_four/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request,'basic_app/index.html', context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

Django_level_four/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="navbar-nav mr-auto">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'basic_app:other' %}">OTHER</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>
  </body>
</html>

Django_level_four/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to INDEX!</h1>
    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ number|add:"200" }}</h1>

  {% endblock %}

Django_level_four/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to OTHER!</h1>
    <h2>This is an example of template inheritance</h2>
  {% endblock %}

Django_level_four/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to Relative URL Templates</h1>
    <a href="{% url 'basic_app:other' %}">OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">ADMIN PAGE</a>
    <a href="{% url 'index' %}">INDEX PAGE</a>
  </body>
</html>